{
  "slug": "teste",
  "version": "1",
  "domain": "tste",
  "entry_type": "teste",
  "description": "teste",
  "limits": null,
  "policies": null,
  "steps": [
    {
      "ordem": 1,
      "tipo_etapa": "interprete",
      "agent_role": "agent_role_exemplo"
    },
    {
      "ordem": 2,
      "tipo_etapa": "classificador",
      "agent_role": "teste"
    },
    {
      "ordem": 3,
      "tipo_etapa": "analista",
      "agent_role": "teste"
    },
    {
      "ordem": 4,
      "tipo_etapa": "decision_maker",
      "agent_role": "teste"
    }
  ],
  "metadata": {},
  "id": null
}