import { env } from '../config/env';

export const endpoints = {
  consult: env.consultationPath,
  auth: {
    login: '/auth/login',
  },
  admin: {
    health: '/admin/health',
    sources: '/admin/sources',
    sourceDetail: (sourceId: string) => `/admin/sources/${encodeURIComponent(sourceId)}`,
    cases: '/admin/cases',
    caseDetail: (caseId: string) => `/admin/cases/${encodeURIComponent(caseId)}`,
    timeline: (caseId: string) => `/admin/cases/${encodeURIComponent(caseId)}/timeline`,
    xray: (caseId: string) => `/admin/cases/${encodeURIComponent(caseId)}/xray`,
    copiloto: {
      sessions: '/admin/copiloto-fontes/sessions',
      messages: (sessionId: string) => `/admin/copiloto-fontes/sessions/${encodeURIComponent(sessionId)}/messages`,
      files: (sessionId: string) => `/admin/copiloto-fontes/sessions/${encodeURIComponent(sessionId)}/files`,
    },
    ingestion: {
      run: (sourceId: string) => `/admin/ingestion/${encodeURIComponent(sourceId)}/run`,
      toggleMode: (sourceId: string) => `/admin/ingestion/${encodeURIComponent(sourceId)}/toggle-mode`,
      runsBySource: (sourceId: string) => `/admin/ingestion/${encodeURIComponent(sourceId)}/runs`,
      runDetail: (runId: string) => `/admin/ingestion/runs/${encodeURIComponent(runId)}`,
    },
    agents: {
      list: '/api/console/agents',
      detail: (agentId: string) => `/api/console/agents/${encodeURIComponent(agentId)}`,
      instructions: (agentId: string) => `/api/console/agents/${encodeURIComponent(agentId)}/instructions`,
      committees: '/api/console/agents/committees',
      committeeDetail: (committeeId: string) => `/api/console/agents/committees/${encodeURIComponent(committeeId)}`,
      committeeRuns: (committeeId: string) => `/api/console/agents/committees/${encodeURIComponent(committeeId)}/runs`,
      committeeDryRun: (committeeId: string) => `/api/console/agents/committees/${encodeURIComponent(committeeId)}/dry-run`,
      modelPolicy: '/api/console/agents/policies/model-upgrades',
      flow: '/api/console/agents/flow',
      flowsAdmin: '/admin/agent-flows',
      flowAdminDetail: (flowId: string) => `/admin/agent-flows/${encodeURIComponent(flowId)}`,
      flowAdminByDomain: (domainKey: string) => `/admin/agent-flows/by-domain/${encodeURIComponent(domainKey)}`,
    },
    providers: {
      list: '/api/providers',
      detail: (providerId: string) => `/api/providers/${encodeURIComponent(providerId)}`,
      profiles: '/api/providers/profiles',
      profileDetail: (profileId: string) => `/api/providers/profiles/${encodeURIComponent(profileId)}`,
      profileRuns: (profileId: string) => `/api/providers/profiles/${encodeURIComponent(profileId)}/runs`,
      profileMetrics: (profileId: string) => `/api/providers/profiles/${encodeURIComponent(profileId)}/metrics`,
      profileRunNow: (profileId: string) => `/api/providers/profiles/${encodeURIComponent(profileId)}/run-now`,
    },
    flows: {
      list: '/api/flows',
      templates: '/api/flows/templates',
      templateDetail: (slug: string) => `/api/flows/templates/${encodeURIComponent(slug)}`,
      detail: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}`,
      createFromTemplate: '/api/flows/from_template',
      updateState: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/state`,
      replaceAgent: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/replace_agent`,
      executions: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/executions`,
      executionDetail: (flowId: string, execId: string) =>
        `/api/flows/${encodeURIComponent(flowId)}/executions/${encodeURIComponent(execId)}`,
      reprocess: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/reprocess`,
      versions: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/versions`,
      versionDetail: (flowId: string, versionId: string) =>
        `/api/flows/${encodeURIComponent(flowId)}/versions/${encodeURIComponent(versionId)}`,
      rollback: (flowId: string, versionId: string) =>
        `/api/flows/${encodeURIComponent(flowId)}/versions/${encodeURIComponent(versionId)}/rollback`,
      operations: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/ops`,
      catalog: `/api/flows/catalog/list`,
      rollout: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/rollout`,
      rolloutPromote: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/promote`,
      rolloutRollback: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/rollback_rollout`,
      rolloutStatus: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/rollout/status`,
    },
    opsCockpit: {
      overview: '/api/ops/cockpit/overview',
      components: '/api/ops/cockpit/components',
      incidents: '/api/ops/cockpit/incidents',
      flows: '/api/ops/cockpit/flows',
    },
    newsdata: {
      run: '/api/ingest/newsdata/run',
    },
    traces: {
      recent: (domain?: string) => `/api/traces/recent${domain ? `?domain=${encodeURIComponent(domain)}` : ''}`,
      byDecision: (decisionId: string) => `/api/traces/decision/${encodeURIComponent(decisionId)}`,
      detail: (traceId: string) => `/api/traces/${encodeURIComponent(traceId)}`,
      feedbackTrace: '/api/feedback/trace',
      feedbackDecision: '/api/feedback/decision',
    },
    guardian: {
      decisions: '/api/guardian/decisions',
      decisionDetail: (decisionId: string) => `/api/guardian/decisions/${encodeURIComponent(decisionId)}`,
      decisionBlock: (decisionId: string) => `/api/guardian/decisions/${encodeURIComponent(decisionId)}/block`,
      decisionCommittee: (decisionId: string) => `/api/guardian/decisions/${encodeURIComponent(decisionId)}/committee`,
      awaitingReview: '/api/guardian/decisions/awaiting-review',
      awaitingQuorum: '/api/guardian/decisions/awaiting-quorum',
      submitReview: (decisionId: string) => `/api/guardian/decisions/${encodeURIComponent(decisionId)}/review`,
      submitVote: (decisionId: string) => `/api/guardian/decisions/${encodeURIComponent(decisionId)}/vote`,
      reviewQueue: '/api/guardian/review-queue',
      reviewQueueStats: '/api/guardian/review-queue/stats',
      metrics: '/api/guardian/metrics',
      policies: '/api/guardian/policies',
      policyDetail: (policyName: string) => `/api/guardian/policies/${encodeURIComponent(policyName)}`,
    },
  },
};
